### ISSUE TITLE
[Task] Get manuscript code and data ready for submission

### ISSUE THREAD

**Issue by gsvidaurre** [lastralab/ABISSMAL#463]
- [x]  Update code for manuscript data processing and generating figures
- [x] Rerun code for manuscript data processing and generating figures
- [x] Write up metadata for data sharing
- [x] Make manuscript code available on GitHub
- [x] Make raw and processed data for manuscript available on figshare or Dryad
